import "./globals.css";
export const metadata = {
  title: "WolWha",
  description: "Generated by WolWha",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
// 서로 다른 레이아웃의 페이지가 필요하면 새로운 레이어를 만들면 된다.
// 루트 레이아웃은 최대한 건드리지 않는다.
