import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: {
    default: "Next.js | Wolwha",
    template: "%s | Wolwha",
    // 타이틀에 대한 템플릿 지정
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <br />
      <Link href="/about">/about</Link>
      <br />
      <Link href="/blog">/blog</Link>
      <br />
    </html>
  );
}
// 서로 다른 레이아웃의 페이지가 필요하면 새로운 레이어를 만들면 된다.
// 루트 레이아웃은 최대한 건드리지 않는다.
